# Generated by Django 5.2.14 on 2026-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
